name: AI-Powered Code Review

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests gitpython

      - name: Fetch PR Diff
        id: get_diff
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
        run: |
          pr_number="${{ github.event.number }}"
          repo_name="${{ github.repository }}"
          pr_url="https://api.github.com/repos/$repo_name/pulls/$pr_number"
          # Fetch PR diff and store in an output variable
          diff=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$pr_url" | jq -r '.diff_url')
          echo "PR URL: $pr_url"
          echo "PR Diff URL: $diff"
          echo "::set-output name=pr_url::$pr_url"
          echo "::set-output name=pr_diff::$diff"

      - name: Run Performance Review Script
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/performance_review.py "${{ steps.get_diff.outputs.pr_url }}" "${{ steps.get_diff.outputs.pr_diff }}"

      - name: Run Developer Assignment Script
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pr_number="${{ github.event.number }}"
          repo_name="${{ github.repository }}"
          pr_url="https://api.github.com/repos/$repo_name/pulls/$pr_number"
          echo $pr_url
          python scripts/developer_assignment.py "$pr_url" "$repo_name"

      - name: Run Testing Suggestions Script
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/testing_suggestions.py  "${{ steps.get_diff.outputs.pr_url }}" "${{ steps.get_diff.outputs.pr_diff }}"

      - name: Run Conflict Detection Script
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Set variables from the GitHub context for PR details
          pr_number="${{ github.event.number }}"
          repo_name="${{ github.repository }}"
          pr_url="https://api.github.com/repos/$repo_name/pulls/$pr_number"
          base_branch="${{ github.event.pull_request.base.ref }}"
          head_branch="${{ github.event.pull_request.head.ref }}"
          
          # Run the conflict_detection.py script with parameters
          python scripts/conflict_detection.py "$pr_url" "$base_branch" "$head_branch" "$repo_name"

      - name: Run Performance Review Script
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/performance_review.py "${{ steps.get_diff.outputs.pr_url }}" "${{ steps.get_diff.outputs.pr_diff }}"

