name: AI-Powered Code Review

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests gitpython

      - name: Run Developer Assignment Script
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/developer_assignment.py

      - name: Run Testing Suggestions Script
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/testing_suggestions.py

      - name: Run Conflict Detection Script
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/conflict_detection.py

      - name: Run Performance Review Script
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/performance_review.py

